In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('D:/Users/RISHABH/anaconda3/6.1 Machine_Learning_A-Z_New.zip/Machine Learning A-Z New/Part 2 - Regression/Section 5 - Multiple Linear Regression/insurance.csv')

In [3]:
df

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [4]:
X = df.iloc[:, :-1].values

In [5]:
y = df.iloc[:,6].values

In [6]:
X

array([[19, 'female', 27.9, 0, 'yes', 'southwest'],
       [18, 'male', 33.77, 1, 'no', 'southeast'],
       [28, 'male', 33.0, 3, 'no', 'southeast'],
       ...,
       [18, 'female', 36.85, 0, 'no', 'southeast'],
       [21, 'female', 25.8, 0, 'no', 'southwest'],
       [61, 'female', 29.07, 0, 'yes', 'northwest']], dtype=object)

In [7]:
y

array([16884.924 ,  1725.5523,  4449.462 , ...,  1629.8335,  2007.945 ,
       29141.3603])

In [8]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
le_X = LabelEncoder()
X[:,1] = le_X.fit_transform(X[:, 1])
X[:,4] = le_X.fit_transform(X[:, 4])
X[:,5] = le_X.fit_transform(X[:, 5])

In [9]:
ohe_X = OneHotEncoder(categories= [1,4,5])

In [10]:
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(
        [('one_hot_encoder' , OneHotEncoder(categories = 'auto'),[1,4,5])],
        remainder = 'passthrough'
)

In [11]:
X = ct.fit_transform(X)

In [13]:
X[1,:]

array([0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 18, 33.77, 1], dtype=object)

In [14]:
X = X[:,[1,2,4,6,7,8,9,10]]

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.25, random_state = 0)

In [16]:
X_train

array([[0.0, 1.0, 0.0, ..., 32, 29.59, 1],
       [0.0, 1.0, 1.0, ..., 61, 22.04, 0],
       [1.0, 1.0, 0.0, ..., 19, 24.6, 1],
       ...,
       [1.0, 1.0, 0.0, ..., 40, 25.08, 0],
       [1.0, 1.0, 0.0, ..., 19, 35.53, 0],
       [0.0, 1.0, 0.0, ..., 33, 18.5, 1]], dtype=object)

In [17]:
y_train

array([ 4562.8421, 13616.3586,  1837.237 , ...,  5415.6612,  1646.4297,
        4766.022 ])

In [18]:
X_test

array([[1.0, 1.0, 0.0, ..., 52, 30.2, 1],
       [0.0, 1.0, 0.0, ..., 47, 29.37, 1],
       [1.0, 0.0, 0.0, ..., 48, 40.565, 2],
       ...,
       [1.0, 1.0, 0.0, ..., 51, 30.03, 1],
       [1.0, 1.0, 0.0, ..., 23, 37.1, 3],
       [0.0, 0.0, 0.0, ..., 61, 29.07, 0]], dtype=object)

In [19]:
y_test

array([ 9724.53    ,  8547.6913  , 45702.02235 , 12950.0712  ,
        9644.2525  ,  4500.33925 ,  2198.18985 , 11436.73815 ,
        7537.1639  ,  5425.02335 ,  6753.038   , 10493.9458  ,
        7337.748   ,  4185.0979  , 18310.742   , 10702.6424  ,
       12523.6048  ,  3490.5491  ,  6457.8434  , 33475.81715 ,
       23967.38305 , 12643.3778  , 23045.56616 , 23065.4207  ,
        1674.6323  ,  4667.60765 ,  3732.6251  ,  7682.67    ,
        3756.6216  ,  8413.46305 ,  8059.6791  , 48970.2476  ,
       12979.358   , 20630.28351 , 14571.8908  ,  4137.5227  ,
        8347.1643  , 51194.55914 , 40003.33225 ,  1880.487   ,
        5458.04645 ,  2867.1196  , 20149.3229  , 47496.49445 ,
       36149.4835  , 26018.95052 , 19749.38338 ,  6940.90985 ,
        4718.20355 , 22192.43711 ,  2899.48935 , 18838.70366 ,
       23568.272   , 46255.1125  , 24227.33724 ,  3268.84665 ,
        2322.6218  ,  8827.2099  , 14478.33015 , 13112.6048  ,
        1253.936   , 46718.16325 , 13919.8229  ,  9630.

In [20]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [21]:
y_pred = regressor.predict(X_test)

In [22]:
y_pred

array([11121.10140924,  9369.08345223, 38349.2588068 , 16331.93500645,
        7041.22770615,  4103.24923177,  1734.03805961, 14478.86491464,
        9168.77981235,  7715.94671029,  4625.04765547, 10398.53755318,
        8756.48015868,  3738.25833927, 28190.41129687, 10600.67828764,
       11395.63055992,  6248.83935385,  8423.19721152, 27360.73273479,
       33843.62542848, 14432.50562897, 11759.04359894, 32070.2132407 ,
        4152.83526684,  9364.57488075,  1227.5561631 ,  9712.31328139,
        3714.56843696, 10585.88359557,  9162.47300707, 39963.69536536,
       15580.1455371 , 13795.75096539, 24960.11670118,  5274.13784945,
       12507.41956494, 30840.51073591, 33738.39701967,  3693.97640602,
        4083.679354  ,  3960.78010537, 30688.77955811, 39647.57881672,
       27822.13821979,  5297.22284982, 10490.69035982,  8000.03303241,
        3721.57055488, 10074.13524545,  5834.48592072,  3655.97278651,
       33043.86058963, 38550.26073255, 15858.08435828,  7288.48878169,
      

In [23]:
regressor.coef_

array([ 1.32630725e+01, -2.36566205e+04,  1.93132934e+02, -8.86668722e+02,
       -6.75310782e+02,  2.50152128e+02,  3.33296751e+02,  4.42213760e+02])

In [24]:
regressor.intercept_

11924.083363784324

In [25]:
regressor.score(X_train,y_train)

0.7340594348890694

In [26]:
regressor.score(X_test,y_test)

0.7958786376014415