In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
train_data = pd.read_csv('train.csv')

In [3]:
train_data.head()

Product_id  Stall_no             instock_date  Market_Category  \
0  BRAE2NF6JA5GUEXG      37.0  2015-08-22 18:36:12.000                2   
1  TUNE8SFB6RJN2HSD      38.0  2016-03-27 21:19:13.000               24   
2  BRAEAR7WZPQGPBZU       9.0  2015-08-18 19:25:22.000              447   
3  WATDZ2ZQ8JPDHCTJ      50.0  2016-03-28 21:53:01.000               23   
4  JWSEBUKYQPMBZ3RK       7.0  2016-03-29 22:58:53.000               63   

  Customer_name Loyalty_customer Product_Category  Grade  Demand  \
0      Lillyann              Yes          Fashion      1      68   
1         Klynn              Yes          Fashion      0      51   
2         Ridge              Yes       Child_care      0      10   
3         Abran              Yes      Educational      2      48   
4        Dustyn              Yes           Repair      1      35   

   Discount_avail  charges_1  charges_2 (%)  Minimum_price  Maximum_price  \
0             0.0      376.0           11.0         2983.0         4713.0   
1             0.0      397.0           12.0         7495.0        10352.0   
2             0.0      250.0            9.0         5752.0         7309.0   
3             0.0      144.0           13.0         5090.0        20814.0   
4             1.0      211.0            4.0         2430.0         9261.0   

   Selling_Price  
0    4185.947700  
1    9271.490256  
2    6785.701362  
3   13028.917824  
4     906.553935

In [4]:
train_data.isnull().sum()

Product_id            0
Stall_no              5
instock_date          0
Market_Category       0
Customer_name       211
Loyalty_customer      0
Product_Category      0
Grade                 0
Demand                0
Discount_avail       38
charges_1           198
charges_2 (%)       205
Minimum_price        38
Maximum_price       343
Selling_Price        41
dtype: int64

In [5]:
train_data

Product_id  Stall_no             instock_date  Market_Category  \
0     BRAE2NF6JA5GUEXG      37.0  2015-08-22 18:36:12.000                2   
1     TUNE8SFB6RJN2HSD      38.0  2016-03-27 21:19:13.000               24   
2     BRAEAR7WZPQGPBZU       9.0  2015-08-18 19:25:22.000              447   
3     WATDZ2ZQ8JPDHCTJ      50.0  2016-03-28 21:53:01.000               23   
4     JWSEBUKYQPMBZ3RK       7.0  2016-03-29 22:58:53.000               63   
...                ...       ...                      ...              ...   
6363  WATE7VE2D62VEKW8      17.0  2016-03-28 19:55:43.000               24   
6364  SHOEF9G8Z4ZXF6WE      21.0  2015-02-11 15:09:26.000               55   
6365  PBXEB9ZQ7HHCFXYG      36.0  2015-11-19 17:29:21.000              358   
6366  NKCEAGXHRYTNTMG7      27.0  2015-12-08 04:19:33.000              452   
6367  CAGE53FSAFWZRHFF      11.0  2016-01-20 19:45:35.000               58   

     Customer_name Loyalty_customer Product_Category  Grade  Demand  \
0         Lillyann              Yes          Fashion      1      68   
1            Klynn              Yes          Fashion      0      51   
2            Ridge              Yes       Child_care      0      10   
3            Abran              Yes      Educational      2      48   
4           Dustyn              Yes           Repair      1      35   
...            ...              ...              ...    ...     ...   
6363      Marquell              Yes       Technology      0      47   
6364      Theodore              Yes       Child_care      0      35   
6365         Galen              No            Repair      3      29   
6366         Posey              Yes           Repair      0       8   
6367        Cutler              Yes       Technology      0      94   

      Discount_avail  charges_1  charges_2 (%)  Minimum_price  Maximum_price  \
0                0.0      376.0           11.0         2983.0         4713.0   
1                0.0      397.0           12.0         7495.0        10352.0   
2                0.0      250.0            9.0         5752.0         7309.0   
3                0.0      144.0           13.0         5090.0        20814.0   
4                1.0      211.0            4.0         2430.0         9261.0   
...              ...        ...            ...            ...            ...   
6363             0.0      614.0           10.0         8174.0        11266.0   
6364             0.0      269.0            5.0         3564.0         4920.0   
6365             0.0      283.0            3.0         5303.0        14614.0   
6366             0.0      267.0            3.0         4334.0         5849.0   
6367             0.0      614.0            7.0         3975.0         5383.0   

      Selling_Price  
0       4185.947700  
1       9271.490256  
2       6785.701362  
3      13028.917824  
4        906.553935  
...             ...  
6363   10277.520192  
6364    4501.837200  
6365   10218.878775  
6366    5359.493997  
6367    5220.013568  

[6368 rows x 15 columns]

In [6]:
train_data['Stall_no'] = train_data['Stall_no'].fillna(train_data['Stall_no'].mean())
train_data['Discount_avail'] = train_data['Discount_avail'].fillna(train_data['Discount_avail'].mean())
train_data['charges_1'] = train_data['charges_1'].fillna(train_data['charges_1'].mean())
train_data['charges_2 (%)'] = train_data['charges_2 (%)'].fillna(train_data['charges_2 (%)'].mean())
train_data['Minimum_price'] = train_data['Minimum_price'].fillna(train_data['Minimum_price'].mean())
train_data['Maximum_price'] = train_data['Maximum_price'].fillna(train_data['Maximum_price'].mean())
train_data['Selling_Price'] = train_data['Selling_Price'].fillna(train_data['Selling_Price'].mean())

In [7]:
train_data.isnull().sum()

Product_id            0
Stall_no              0
instock_date          0
Market_Category       0
Customer_name       211
Loyalty_customer      0
Product_Category      0
Grade                 0
Demand                0
Discount_avail        0
charges_1             0
charges_2 (%)         0
Minimum_price         0
Maximum_price         0
Selling_Price         0
dtype: int64

In [8]:
test_data = pd.read_csv('test.csv')

In [9]:
test_data.head()

Product_id  Stall_no             instock_date  Market_Category  \
0  SCHE4YSTDVPVZVXW      39.0  2016-01-13 07:45:08.000              205   
1  ACCEGCATKHNRXUHW      49.0  2015-08-23 20:37:05.000                3   
2  NKCE6GJ5XVJDXNNZ       1.0  2015-11-14 18:12:39.000              183   
3  NKCEB8BK3ZXDHDHM       8.0  2015-11-21 04:56:19.000              358   
4  TOPEFDXSAHRNPF94      33.0  2015-05-06 15:09:46.000              167   

  Customer_name Loyalty_customer Product_Category  Grade  Demand  \
0        Ivanka              No           Fashion      0      90   
1         Isaak              Yes          Fashion      0      87   
2      Analiese              No        Technology      2      55   
3         Rusty              Yes       Child_care      3      86   
4        Eloise              No        Technology      0      27   

   Discount_avail  charges_1  charges_2 (%)  Minimum_price  Maximum_price  
0               0      380.0           16.0         2576.0           3340  
1               0      393.0           16.0         1202.0           1955  
2               0      493.0            9.0         7175.0          15715  
3               0      303.0           16.0         5404.0          13078  
4               0      567.0           16.0         4069.0           6244

In [10]:
test_data['Stall_no'] = test_data['Stall_no'].fillna(test_data['Stall_no'].mean())
test_data['Discount_avail'] = test_data['Discount_avail'].fillna(test_data['Discount_avail'].mean())
test_data['charges_1'] = test_data['charges_1'].fillna(test_data['charges_1'].mean())
test_data['charges_2 (%)'] = test_data['charges_2 (%)'].fillna(test_data['charges_2 (%)'].mean())
test_data['Minimum_price'] = test_data['Minimum_price'].fillna(test_data['Minimum_price'].mean())
test_data['Maximum_price'] = test_data['Maximum_price'].fillna(test_data['Maximum_price'].mean())


In [11]:
train_id = train_data['Product_id']

In [12]:
train_id.head()

0    BRAE2NF6JA5GUEXG
1    TUNE8SFB6RJN2HSD
2    BRAEAR7WZPQGPBZU
3    WATDZ2ZQ8JPDHCTJ
4    JWSEBUKYQPMBZ3RK
Name: Product_id, dtype: object

In [13]:
x_train = train_data.iloc[:,[1,3,5,6,7,8,9,10,11,12,13]].values
y_train = train_data.iloc[:,14].values

In [14]:
x_train


array([[37.0, 2, 'Yes', ..., 11.0, 2983.0, 4713.0],
       [38.0, 24, 'Yes', ..., 12.0, 7495.0, 10352.0],
       [9.0, 447, 'Yes', ..., 9.0, 5752.0, 7309.0],
       ...,
       [36.0, 358, 'No ', ..., 3.0, 5303.0, 14614.0],
       [27.0, 452, 'Yes', ..., 3.0, 4334.0, 5849.0],
       [11.0, 58, 'Yes', ..., 7.0, 3975.0, 5383.0]], dtype=object)

In [15]:
x_test = test_data.iloc[:,[1,3,5,6,7,8,9,10,11,12,13]].values

In [16]:
test_id = test_data['Product_id']

In [17]:
x_train

array([[37.0, 2, 'Yes', ..., 11.0, 2983.0, 4713.0],
       [38.0, 24, 'Yes', ..., 12.0, 7495.0, 10352.0],
       [9.0, 447, 'Yes', ..., 9.0, 5752.0, 7309.0],
       ...,
       [36.0, 358, 'No ', ..., 3.0, 5303.0, 14614.0],
       [27.0, 452, 'Yes', ..., 3.0, 4334.0, 5849.0],
       [11.0, 58, 'Yes', ..., 7.0, 3975.0, 5383.0]], dtype=object)

In [18]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
le_train1 = LabelEncoder()
le_train2 = LabelEncoder()
x_train[:,2] = le_train1.fit_transform(x_train[:,2])
x_train[:,3] = le_train2.fit_transform(x_train[:,3])

In [19]:
x_train[:5,:]

array([[37.0, 2, 1, 3, 1, 68, 0.0, 376.0, 11.0, 2983.0, 4713.0],
       [38.0, 24, 1, 3, 0, 51, 0.0, 397.0, 12.0, 7495.0, 10352.0],
       [9.0, 447, 1, 0, 0, 10, 0.0, 250.0, 9.0, 5752.0, 7309.0],
       [50.0, 23, 1, 2, 2, 48, 0.0, 144.0, 13.0, 5090.0, 20814.0],
       [7.0, 63, 1, 8, 1, 35, 1.0, 211.0, 4.0, 2430.0, 9261.0]],
      dtype=object)

In [20]:
x_train[:,3]

array([3, 3, 0, ..., 8, 8, 9], dtype=object)

In [21]:
le_test1 = LabelEncoder()
le_test2 = LabelEncoder()
x_test[:,2] = le_test1.fit_transform(x_test[:,2])
x_test[:,3] = le_test2.fit_transform(x_test[:,3])

In [22]:
x_test

array([[39.0, 205, 0, ..., 16.0, 2576.0, 3340],
       [49.0, 3, 1, ..., 16.0, 1202.0, 1955],
       [1.0, 183, 0, ..., 9.0, 7175.0, 15715],
       ...,
       [14.0, 106, 1, ..., 17.0, 710.0, 10894],
       [1.0, 104, 1, ..., 15.0, 1477.0, 5165],
       [3.0, 165, 0, ..., 9.0, 5538.0, 7506]], dtype=object)

In [23]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [24]:
x_train

array([[ 0.81625254, -1.15903947,  0.79892518, ...,  0.2009938 ,
        -0.25061705, -0.47574736],
       [ 0.88607408, -1.02982699,  0.79892518, ...,  0.43640329,
         1.81154148,  1.08439672],
       [-1.13875058,  1.45457648,  0.79892518, ..., -0.2698252 ,
         1.01492306,  0.24248886],
       ...,
       [ 0.746431  ,  0.93185329, -1.25168166, ..., -1.68228218,
         0.80971269,  2.26356573],
       [ 0.11803714,  1.48394295,  0.79892518, ..., -1.68228218,
         0.36684221, -0.16144984],
       [-0.9991075 , -0.83013499,  0.79892518, ..., -0.74064419,
         0.20276532, -0.29037822]])

In [25]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import ShuffleSplit
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR

In [26]:
import keras
from keras.layers import Dense
from keras.models import Sequential

In [ ]:
# def find_best_model(X,Y):
#     models = {
#         'linear_regression' :{
#             'model': LinearRegression(),
#             'parameters':{
                
#             }
#         },
        
#         'decison_tree_regressor':{
#             'model': DecisionTreeRegressor(splitter='best'),
#             'parameters' :{
#                 'max_depth' :[5,10]
#             }
#         },
        
#         'random_forest': {
#             'model': RandomForestRegressor(),
            
#             'parameters' :{
#                 'n_estimators': [1,5,10,15,20,30,40,50,60,70,80,90,100]
#             }
#         },
        
#         'svc' : {
#             'model' : SVR(gamma= 'auto'),
            
#             'parameters': {
#                 'kernel' : ['rbf','linear'],
#                 'C': [1,10,20]
#             }
#         }
#     }
    
#     scores = []
#     cv_shuffle = ShuffleSplit(n_splits=5,test_size= 0.2,random_state=0)
    
#     for model_names,model_params in models.items():
#         gc = GridSearchCV(model_params['model'],model_params['parameters'],cv = cv_shuffle,return_train_score= False)
#         gc.fit(X,Y)
#         scores.append({
#             'model': model_names,
#             'parameters' : gc.best_params_,
#             'score' : gc.best_score_
#         })
        
#     return pd.DataFrame(scores, columns=['model','best_parameters','score'])

# find_best_model(x_train, y_train)

In [ ]:
regressor = RandomForestRegressor(n_estimators= 80)
regressor.fit(x_train,y_train)

In [ ]:
predictions = regressor.predict(x_test)

In [ ]:
predictions

In [ ]:
predictions.shape

In [ ]:
test_data.shape

In [ ]:
data = pd.DataFrame((zip(test_id,predictions)),columns=['Product_id','Selling_Price'])

In [ ]:
data

In [ ]:
data.to_csv('output.csv',index= False)